// SPDX-License-Identifier: MIT

#include "private/VkStylePainter_p.h"
#include "private/VkStyle_p.h"
#include "private/VkWidgetAnimationManager_p.h"

#include <QAbstractButton>
#include <QAbstractItemView>
#include <QAbstractSpinBox>
#include <QApplication>
#include <QComboBox>
#include <QEvent>
#include <QFrame>
#include <QHash>
#include <QPainter>
#include <QPointer>
#include <QRegion>
#include <QStyleFactory>
#include <QStyleHintReturn>
#include <QStyleOptionButton>
#include <QStyleOptionComboBox>
#include <QStyleOptionComplex>
#include <QStyleOptionFrame>
#include <QStyleOptionGroupBox>
#include <QStyleOptionHeader>
#include <QStyleOptionMenuItem>
#include <QStyleOptionProgressBar>
#include <QStyleOptionSlider>
#include <QStyleOptionSpinBox>
#include <QStyleOptionTab>
#include <QStyleOptionToolButton>
#include <QStyleOptionViewItem>
#include <QTimer>
#include <QWidget>
#include <algorithm>
#include <array>
#include <cmath>
#include <mutex>
#include <vkui/core/VkIcon.h>
#include <vkui/core/VkTheme.h>
#include <vkui/core/VkThemeManager.h>
#include <vkui/widgets/VkComboBox.h>
#include <vkui/widgets/VkControlSize.h>
#include <vkui/widgets/style/VkStyle.h>

static void initializeVkUiResources() {
    // This helper intentionally lives in the global namespace because the Qt
    // resource initializer generated by rcc has global namespace linkage.
    Q_INIT_RESOURCE(vkui);
}

namespace {

bool hasState(const QStyleOption* option, QStyle::StateFlag state) {
    return option && option->state.testFlag(state);
}

QRectF insetRect(const QRect& rect, qreal inset) {
    return QRectF(rect).adjusted(inset, inset, -inset, -inset);
}

bool isEmbeddedEditor(const QWidget* widget) {
    const QWidget* parent = widget ? widget->parentWidget() : nullptr;
    return widget && widget->inherits("QLineEdit") && parent &&
           (qobject_cast<const QAbstractSpinBox*>(parent) ||
            qobject_cast<const QComboBox*>(parent));
}

Qt::ArrowType arrowTypeForPrimitive(QStyle::PrimitiveElement element) {
    switch (element) {
    case QStyle::PE_IndicatorArrowLeft:
        return Qt::LeftArrow;
    case QStyle::PE_IndicatorArrowRight:
        return Qt::RightArrow;
    case QStyle::PE_IndicatorArrowUp:
        return Qt::UpArrow;
    case QStyle::PE_IndicatorArrowDown:
    default:
        return Qt::DownArrow;
    }
}

} // namespace

namespace vkui {

class VkPopupSurfaceStyler final : public QObject {
  public:
    explicit VkPopupSurfaceStyler(QObject* parent) : QObject(parent) {}

    ~VkPopupSurfaceStyler() override {
        const auto popups = m_popups.keys();
        for (QWidget* popup : popups) {
            unpolish(popup);
        }
    }

    static bool isComboPopupContainer(const QWidget* widget) {
        return widget && widget->inherits("QComboBoxPrivateContainer");
    }

    static bool isMenuPopup(const QWidget* widget) {
        return widget && widget->inherits("QMenu");
    }

    static bool isPopupContainer(const QWidget* widget) {
        return isComboPopupContainer(widget) || isMenuPopup(widget);
    }

    bool isPopupPart(const QWidget* widget) const {
        for (const QWidget* candidate = widget; candidate; candidate = candidate->parentWidget()) {
            if (isPopupContainer(candidate)) {
                return true;
            }
        }
        return false;
    }

    void polish(QWidget* popup) {
        if (!isPopupContainer(popup) || m_popups.contains(popup)) {
            return;
        }

        PopupState state;
        state.translucentBackground = popup->testAttribute(Qt::WA_TranslucentBackground);
        state.noSystemBackground = popup->testAttribute(Qt::WA_NoSystemBackground);
        state.opaquePaintEvent = popup->testAttribute(Qt::WA_OpaquePaintEvent);
        state.styledBackground = popup->testAttribute(Qt::WA_StyledBackground);
        state.autoFillBackground = popup->autoFillBackground();
        state.palette = popup->palette();
        state.mask = popup->mask();
        state.windowFlags = popup->windowFlags();
        m_popups.insert(popup, state);

        popup->setAttribute(Qt::WA_TranslucentBackground, true);
        popup->setAttribute(Qt::WA_NoSystemBackground, true);
        popup->setAttribute(Qt::WA_OpaquePaintEvent, false);
        popup->setAttribute(Qt::WA_StyledBackground, false);
        popup->setAutoFillBackground(false);
        applyTransparentPalette(*popup);
        popup->clearMask();
#if defined(Q_OS_WIN)
        // Qt requires a frameless top-level window for translucent QWidget
        // backgrounds on Windows. Setting it explicitly keeps the compositing
        // contract stable for both QComboBox and QMenu popups.
        popup->setWindowFlag(Qt::FramelessWindowHint, true);
        popup->setWindowFlag(Qt::NoDropShadowWindowHint, true);
#endif
        popup->installEventFilter(this);
        connect(popup, &QObject::destroyed, this, [this, popup] { m_popups.remove(popup); });
        configureView(popup, m_popups[popup]);
        popup->update();
    }

    void unpolish(QWidget* popup) {
        auto iterator = m_popups.find(popup);
        if (iterator == m_popups.end()) {
            return;
        }
        const PopupState state = iterator.value();
        m_popups.erase(iterator);

        popup->removeEventFilter(this);
        popup->setAttribute(Qt::WA_TranslucentBackground, state.translucentBackground);
        popup->setAttribute(Qt::WA_NoSystemBackground, state.noSystemBackground);
        popup->setAttribute(Qt::WA_OpaquePaintEvent, state.opaquePaintEvent);
        popup->setAttribute(Qt::WA_StyledBackground, state.styledBackground);
        popup->setAutoFillBackground(state.autoFillBackground);
        popup->setPalette(state.palette);
#if defined(Q_OS_WIN)
        popup->setWindowFlags(state.windowFlags);
#endif
        if (state.mask.isEmpty()) {
            popup->clearMask();
        } else {
            popup->setMask(state.mask);
        }
        restoreView(state);
    }

  protected:
    bool eventFilter(QObject* watched, QEvent* event) override {
        auto* popup = qobject_cast<QWidget*>(watched);
        if (!popup || !m_popups.contains(popup)) {
            return QObject::eventFilter(watched, event);
        }

        switch (event->type()) {
        case QEvent::Paint: {
            // Clear alpha explicitly because popup surfaces are reused between
            // openings and QWidget's backing store may retain transparent-corner
            // pixels from a previous size.
            QPainter clearPainter(popup);
            clearPainter.setCompositionMode(QPainter::CompositionMode_Source);
            clearPainter.fillRect(popup->rect(), Qt::transparent);
            break;
        }
        case QEvent::Resize:
        case QEvent::Show:
        case QEvent::ChildAdded:
        case QEvent::StyleChange:
        case QEvent::PaletteChange:
            applyTransparentPalette(*popup);
            popup->clearMask();
            configureView(popup, m_popups[popup]);
            popup->update();
            break;
        default:
            break;
        }
        return QObject::eventFilter(watched, event);
    }

  private:
    struct PopupState {
        bool translucentBackground = false;
        bool noSystemBackground = false;
        bool opaquePaintEvent = false;
        bool styledBackground = false;
        bool autoFillBackground = false;
        QPalette palette;
        QRegion mask;
        Qt::WindowFlags windowFlags;
        QPointer<QAbstractItemView> view;
        QPalette viewPalette;
        bool viewAutoFillBackground = false;
        int viewFrameStyle = QFrame::NoFrame;
        QPointer<QWidget> viewport;
        QPalette viewportPalette;
        bool viewportAutoFillBackground = false;
        bool viewportNoSystemBackground = false;
        bool viewportOpaquePaintEvent = false;
    };

    static void applyTransparentPalette(QWidget& widget) {
        QPalette transparent = widget.palette();
        transparent.setColor(QPalette::Base, Qt::transparent);
        transparent.setColor(QPalette::AlternateBase, Qt::transparent);
        transparent.setColor(QPalette::Window, Qt::transparent);
        widget.setPalette(transparent);
    }

    static void configureView(QWidget* popup, PopupState& state) {
        if (!popup || !isComboPopupContainer(popup)) {
            return;
        }
        if (!state.view) {
            auto* view = popup->findChild<QAbstractItemView*>();
            if (!view || !view->viewport()) {
                return;
            }

            state.view = view;
            state.viewPalette = view->palette();
            state.viewAutoFillBackground = view->autoFillBackground();
            state.viewFrameStyle = view->frameStyle();
            state.viewport = view->viewport();
            state.viewportPalette = state.viewport->palette();
            state.viewportAutoFillBackground = state.viewport->autoFillBackground();
            state.viewportNoSystemBackground =
                state.viewport->testAttribute(Qt::WA_NoSystemBackground);
            state.viewportOpaquePaintEvent = state.viewport->testAttribute(Qt::WA_OpaquePaintEvent);
        }

        QPalette transparent = state.view->palette();
        transparent.setColor(QPalette::Base, Qt::transparent);
        transparent.setColor(QPalette::AlternateBase, Qt::transparent);
        transparent.setColor(QPalette::Window, Qt::transparent);
        state.view->setPalette(transparent);
        state.view->setAutoFillBackground(false);
        state.view->setFrameStyle(QFrame::NoFrame);

        if (state.viewport) {
            state.viewport->setPalette(transparent);
            state.viewport->setAutoFillBackground(false);
            state.viewport->setAttribute(Qt::WA_NoSystemBackground, true);
            state.viewport->setAttribute(Qt::WA_OpaquePaintEvent, false);
        }
    }

    static void restoreView(const PopupState& state) {
        if (state.view) {
            state.view->setPalette(state.viewPalette);
            state.view->setAutoFillBackground(state.viewAutoFillBackground);
            state.view->setFrameStyle(state.viewFrameStyle);
        }
        if (state.viewport) {
            state.viewport->setPalette(state.viewportPalette);
            state.viewport->setAutoFillBackground(state.viewportAutoFillBackground);
            state.viewport->setAttribute(Qt::WA_NoSystemBackground,
                                         state.viewportNoSystemBackground);
            state.viewport->setAttribute(Qt::WA_OpaquePaintEvent, state.viewportOpaquePaintEvent);
        }
    }

    QHash<QWidget*, PopupState> m_popups;
};

class VkRuntimeThemeSynchronizer final : public QObject {
  public:
    explicit VkRuntimeThemeSynchronizer(QApplication& application)
        : QObject(&application), application_(&application) {
        connect(VkThemeManager::instance(), &VkThemeManager::themeChanged, this,
                [this](quint64) { scheduleRefresh(); });
    }

  private:
    static int widgetDepth(const QWidget* widget) {
        int depth = 0;
        for (const QWidget* parent = widget ? widget->parentWidget() : nullptr; parent;
             parent = parent->parentWidget()) {
            ++depth;
        }
        return depth;
    }

    void scheduleRefresh() {
        if (refreshPending_) {
            return;
        }
        refreshPending_ = true;

        // Appearance controls commonly emit while their popup is still dispatching an input
        // event. Refresh on the next event-loop turn so popup teardown and theme repolish never
        // mutate the same widget tree reentrantly. Multiple token changes in one turn coalesce.
        QTimer::singleShot(0, this, [this] { refreshWidgets(); });
    }

    void refreshWidgets() {
        refreshPending_ = false;
        QApplication* application = application_.data();
        if (!application) {
            return;
        }

        struct WidgetEntry {
            QPointer<QWidget> widget;
            int depth = 0;
        };

        QList<WidgetEntry> widgets;
        const QWidgetList liveWidgets = QApplication::allWidgets();
        widgets.reserve(liveWidgets.size());
        for (QWidget* widget : liveWidgets) {
            widgets.append({widget, widgetDepth(widget)});
        }

        // Unpolish children before parents, then polish parents before children. This preserves
        // inherited palettes and lets QStyleSheetStyle rebuild its resolved palette from the new
        // application colors instead of retaining values captured by the previous appearance.
        std::ranges::sort(widgets, [](const WidgetEntry& left, const WidgetEntry& right) {
            return left.depth > right.depth;
        });
        for (const WidgetEntry& entry : widgets) {
            const QPointer<QWidget>& widget = entry.widget;
            if (widget && widget->testAttribute(Qt::WA_WState_Polished) && widget->style()) {
                widget->style()->unpolish(widget);
            }
        }

        std::ranges::reverse(widgets);
        for (const WidgetEntry& entry : widgets) {
            const QPointer<QWidget>& widget = entry.widget;
            if (!widget) {
                continue;
            }
            if (widget->testAttribute(Qt::WA_WState_Polished) && widget->style()) {
                widget->style()->polish(widget);
            }
            widget->updateGeometry();
            widget->update();
        }

        for (QWidget* window : QApplication::topLevelWidgets()) {
            if (window) {
                window->update();
            }
        }
    }

    QPointer<QApplication> application_;
    bool refreshPending_ = false;
};

VkStylePrivate::VkStylePrivate(VkStyle* owner)
    : q(owner), animations(new VkWidgetAnimationManager(owner)),
      popupSurfaces(new VkPopupSurfaceStyler(owner)) {}

VkStylePrivate::~VkStylePrivate() = default;

bool VkStylePrivate::supportsAnimations(const QWidget* widget) {
    if (!widget) {
        return false;
    }
    static constexpr std::array supportedClasses = {
        "QPushButton", "QToolButton", "QLineEdit",        "QCheckBox",    "QRadioButton",
        "QComboBox",   "QSlider",     "QAbstractSpinBox", "QProgressBar", "QTabBar",
        "QMenu",       "QListView",   "QTreeView",        "QTableView",   "QHeaderView",
        "QScrollBar",  "QGroupBox",   "QFrame",
    };
    return std::ranges::any_of(
        supportedClasses, [widget](const char* className) { return widget->inherits(className); });
}

VkStyle::VkStyle()
    : QProxyStyle(QStyleFactory::create(QStringLiteral("Fusion"))),
      d(std::make_unique<VkStylePrivate>(this)) {}

VkStyle::~VkStyle() = default;

void VkStyle::drawPrimitive(PrimitiveElement element, const QStyleOption* option, QPainter* painter,
                            const QWidget* widget) const {
    if (!option || !painter) {
        return;
    }

    const VkTheme& theme = VkThemeManager::instance()->theme();
    const auto& colors = theme.colors();
    const auto& metrics = theme.metrics();
    if ((element == PE_PanelLineEdit || element == PE_FrameLineEdit) && isEmbeddedEditor(widget)) {
        // QAbstractSpinBox and editable QComboBox own the only frame. Their private QLineEdit is
        // deliberately surface-less so nested editors never produce a second rounded rectangle.
        return;
    }
    if (d->popupSurfaces->isPopupPart(widget) &&
        (element == PE_Frame || element == PE_FrameMenu || element == PE_PanelMenu)) {
        if (VkPopupSurfaceStyler::isPopupContainer(widget)) {
            VkStylePainter::drawRoundedPanel(*painter, QRectF(option->rect),
                                             metrics.popoverCornerRadius,
                                             colors.elevatedBackground, colors.border,
                                             metrics.borderWidth);
        }
        // The outer popup owns the only frame. Suppressing descendant Fusion
        // frames avoids a rectangular line inside the rounded clipped window.
        return;
    }
    const bool enabled = hasState(option, State_Enabled);
    const bool hovered = hasState(option, State_MouseOver);
    const bool pressed = hasState(option, State_Sunken);
    const bool focused = hasState(option, State_HasFocus);
    const bool selected = hasState(option, State_On) || hasState(option, State_Selected);
    const bool tracksSelection = element == PE_PanelButtonCommand ||
                                 element == PE_PanelButtonTool || element == PE_IndicatorCheckBox ||
                                 element == PE_IndicatorRadioButton;
    const bool itemViewIndicator = element == PE_IndicatorItemViewItemCheck;
    const bool animatedElement =
        tracksSelection || itemViewIndicator || element == PE_PanelLineEdit;
    const bool selectionTarget = selected || hasState(option, State_NoChange);
    VkWidgetAnimationManager::Progress progress{hovered ? 1.0 : 0.0, pressed ? 1.0 : 0.0,
                                                focused ? 1.0 : 0.0, selectionTarget ? 1.0 : 0.0};
    if (animatedElement && !itemViewIndicator) {
        progress = d->animations->progress(const_cast<QWidget*>(widget), hovered, pressed, focused,
                                           tracksSelection && selectionTarget);
    }

    switch (element) {
    case PE_PanelButtonCommand: {
        const auto* button = qstyleoption_cast<const QStyleOptionButton*>(option);
        const bool defaultButton =
            button && button->features.testFlag(QStyleOptionButton::DefaultButton);
        const qreal emphasis = defaultButton ? 1.0 : progress.selection;
        QColor fill = VkStylePainter::mix(colors.controlFill, colors.accent, emphasis);
        const QColor hoverFill =
            VkStylePainter::mix(colors.controlFillHovered, colors.accentHovered, emphasis);
        const QColor pressFill =
            VkStylePainter::mix(colors.controlFillPressed, colors.accentPressed, emphasis);
        fill = VkStylePainter::mix(fill, hoverFill, progress.hover);
        fill = VkStylePainter::mix(fill, pressFill, progress.press);
        QColor border = VkStylePainter::mix(
            colors.border, VkStylePainter::mix(colors.accent, colors.borderStrong, 0.22), emphasis);
        if (!enabled) {
            fill = colors.controlFillDisabled;
            border = VkStylePainter::multiplyAlpha(colors.border, 0.7);
        }
        VkStylePainter::drawRoundedPanel(*painter, QRectF(option->rect),
                                         metrics.cornerRadiusRegular, fill, border,
                                         metrics.borderWidth);
        if (progress.focus > 0.0) {
            VkStylePainter::drawFocusRing(
                *painter, insetRect(option->rect, metrics.spacing2), metrics.cornerRadiusRegular,
                VkStylePainter::multiplyAlpha(
                    VkStylePainter::neutralFocusColor(colors.borderStrong), progress.focus),
                std::max<qreal>(1.0, metrics.borderWidth));
        }
        return;
    }
    case PE_PanelButtonTool: {
        const bool autoRaise = hasState(option, State_AutoRaise);
        if (autoRaise && progress.hover <= 0.0 && progress.press <= 0.0 &&
            progress.selection <= 0.0) {
            return;
        }
        QColor fill =
            VkStylePainter::mix(Qt::transparent, colors.controlFillPressed, progress.selection);
        fill = VkStylePainter::mix(fill, colors.controlFillHovered, progress.hover);
        fill = VkStylePainter::mix(fill, colors.controlFillPressed, progress.press);
        if (!enabled) {
            fill = VkStylePainter::multiplyAlpha(colors.controlFillDisabled, 0.55);
        }
        VkStylePainter::drawRoundedPanel(*painter, insetRect(option->rect, metrics.spacing2),
                                         metrics.cornerRadiusRegular, fill, Qt::transparent, 0.0);
        if (progress.focus > 0.0) {
            VkStylePainter::drawFocusRing(
                *painter, insetRect(option->rect, metrics.spacing2), metrics.cornerRadiusRegular,
                VkStylePainter::multiplyAlpha(
                    VkStylePainter::neutralFocusColor(colors.borderStrong), progress.focus),
                std::max<qreal>(1.0, metrics.borderWidth));
        }
        return;
    }
    case PE_PanelLineEdit: {
        QColor fill = enabled ? colors.contentBackground : colors.controlFillDisabled;
        QColor border = VkStylePainter::mix(colors.border, colors.borderStrong,
                                            std::max(progress.hover * 0.55, progress.focus));
        VkStylePainter::drawRoundedPanel(*painter, QRectF(option->rect),
                                         metrics.cornerRadiusRegular, fill, border,
                                         metrics.borderWidth);
        if (progress.focus > 0.0) {
            VkStylePainter::drawFocusRing(
                *painter, insetRect(option->rect, metrics.spacing2), metrics.cornerRadiusRegular,
                VkStylePainter::multiplyAlpha(
                    VkStylePainter::neutralFocusColor(colors.borderStrong), progress.focus),
                std::max<qreal>(1.0, metrics.borderWidth));
        }
        return;
    }
    case PE_IndicatorCheckBox:
    case PE_IndicatorItemViewItemCheck: {
        const bool partial = hasState(option, State_NoChange);
        QColor fill =
            VkStylePainter::mix(colors.contentBackground, colors.accent, progress.selection);
        const QColor hoverFill = VkStylePainter::mix(colors.controlFillHovered,
                                                     colors.accentHovered, progress.selection);
        const QColor pressFill = VkStylePainter::mix(colors.controlFillPressed,
                                                     colors.accentPressed, progress.selection);
        fill = VkStylePainter::mix(fill, hoverFill, progress.hover);
        fill = VkStylePainter::mix(fill, pressFill, progress.press);
        if (!enabled) {
            fill = colors.controlFillDisabled;
        }
        const QColor selectedBorder = enabled ? colors.accent : colors.border;
        const QColor border =
            VkStylePainter::mix(colors.borderStrong, selectedBorder, progress.selection);
        VkStylePainter::drawRoundedPanel(*painter, QRectF(option->rect), metrics.cornerRadiusSmall,
                                         fill, border, metrics.borderWidth);
        if ((selected || progress.selection > 0.0) && !partial) {
            QColor mark =
                enabled ? QColor(Qt::white) : VkStylePainter::multiplyAlpha(Qt::white, 0.48);
            mark = VkStylePainter::multiplyAlpha(mark, progress.selection);
            VkStylePainter::drawCheckmark(*painter, insetRect(option->rect, 2.5), mark,
                                          std::max<qreal>(1.5, metrics.borderWidth * 1.7));
        } else if (partial) {
            QColor mark =
                enabled ? QColor(Qt::white) : VkStylePainter::multiplyAlpha(Qt::white, 0.48);
            mark = VkStylePainter::multiplyAlpha(mark, progress.selection);
            VkStylePainter::drawHairline(*painter,
                                         QPointF(option->rect.left() + option->rect.width() * 0.27,
                                                 option->rect.center().y()),
                                         QPointF(option->rect.right() - option->rect.width() * 0.27,
                                                 option->rect.center().y()),
                                         mark);
        }
        if (progress.focus > 0.0) {
            VkStylePainter::drawFocusRing(
                *painter, QRectF(option->rect), metrics.cornerRadiusSmall,
                VkStylePainter::multiplyAlpha(
                    VkStylePainter::neutralFocusColor(colors.borderStrong), progress.focus),
                std::max<qreal>(1.0, metrics.borderWidth));
        }
        return;
    }
    case PE_IndicatorRadioButton: {
        QColor fill =
            VkStylePainter::mix(colors.contentBackground, colors.accent, progress.selection);
        const QColor hoverFill = VkStylePainter::mix(colors.controlFillHovered,
                                                     colors.accentHovered, progress.selection);
        const QColor pressFill = VkStylePainter::mix(colors.controlFillPressed,
                                                     colors.accentPressed, progress.selection);
        fill = VkStylePainter::mix(fill, hoverFill, progress.hover);
        fill = VkStylePainter::mix(fill, pressFill, progress.press);
        if (!enabled) {
            fill = colors.controlFillDisabled;
        }
        painter->save();
        painter->setRenderHint(QPainter::Antialiasing, true);
        const QRectF radioRect = insetRect(option->rect, metrics.borderWidth * 0.5);
        const QColor selectedBorder = enabled ? colors.accent : colors.border;
        const QColor border =
            VkStylePainter::mix(colors.borderStrong, selectedBorder, progress.selection);
        painter->setBrush(fill);
        painter->setPen(QPen(border, metrics.borderWidth));
        painter->drawEllipse(radioRect);
        if (selected || progress.selection > 0.0) {
            painter->setPen(Qt::NoPen);
            QColor mark =
                enabled ? QColor(Qt::white) : VkStylePainter::multiplyAlpha(Qt::white, 0.48);
            mark = VkStylePainter::multiplyAlpha(mark, progress.selection);
            painter->setBrush(mark);
            const qreal dotInset =
                radioRect.width() * (0.50 - 0.22 * std::clamp(progress.selection, 0.0, 1.0));
            painter->drawEllipse(radioRect.adjusted(dotInset, dotInset, -dotInset, -dotInset));
        }
        painter->restore();
        if (progress.focus > 0.0) {
            VkStylePainter::drawFocusRing(
                *painter, QRectF(option->rect), option->rect.width() * 0.5,
                VkStylePainter::multiplyAlpha(
                    VkStylePainter::neutralFocusColor(colors.borderStrong), progress.focus),
                std::max<qreal>(1.0, metrics.borderWidth));
        }
        return;
    }
    case PE_FrameFocusRect:
        // Focus is rendered by each supported control using focus-reason-aware,
        // neutral treatment. Suppress Fusion's rectangular blue focus box.
        if (!VkStylePrivate::supportsAnimations(widget)) {
            QProxyStyle::drawPrimitive(element, option, painter, widget);
        }
        return;
    case PE_PanelMenu:
        VkStylePainter::drawRoundedPanel(*painter, QRectF(option->rect),
                                         metrics.popoverCornerRadius, colors.elevatedBackground,
                                         colors.border, metrics.borderWidth);
        return;
    case PE_PanelTipLabel:
        VkStylePainter::drawRoundedPanel(*painter, QRectF(option->rect),
                                         metrics.cornerRadiusRegular, colors.popoverBackground,
                                         colors.border, metrics.borderWidth);
        return;
    case PE_Frame:
    case PE_FrameGroupBox:
        VkStylePainter::drawRoundedPanel(*painter, QRectF(option->rect),
                                         metrics.cornerRadiusRegular, Qt::transparent,
                                         colors.border, metrics.borderWidth);
        return;
    case PE_IndicatorArrowLeft:
    case PE_IndicatorArrowRight:
    case PE_IndicatorArrowUp:
    case PE_IndicatorArrowDown:
        VkStylePainter::drawChevron(*painter, QRectF(option->rect), arrowTypeForPrimitive(element),
                                    enabled ? colors.symbolSecondary : colors.symbolDisabled,
                                    std::max<qreal>(1.25, metrics.borderWidth * 1.5));
        return;
    default:
        QProxyStyle::drawPrimitive(element, option, painter, widget);
        return;
    }
}

void VkStyle::drawControl(ControlElement element, const QStyleOption* option, QPainter* painter,
                          const QWidget* widget) const {
    if (!option || !painter) {
        return;
    }

    const VkTheme& theme = VkThemeManager::instance()->theme();
    const auto& colors = theme.colors();
    const auto& metrics = theme.metrics();
    const bool enabled = hasState(option, State_Enabled);
    const bool hovered = hasState(option, State_MouseOver);
    const bool selected = hasState(option, State_Selected) || hasState(option, State_On);

    switch (element) {
    case CE_PushButton:
        drawControl(CE_PushButtonBevel, option, painter, widget);
        drawControl(CE_PushButtonLabel, option, painter, widget);
        return;
    case CE_PushButtonBevel:
        drawPrimitive(PE_PanelButtonCommand, option, painter, widget);
        return;
    case CE_PushButtonLabel: {
        const auto* button = qstyleoption_cast<const QStyleOptionButton*>(option);
        if (!button) {
            QProxyStyle::drawControl(element, option, painter, widget);
            return;
        }
        QStyleOptionButton copy = *button;
        const bool emphasized =
            selected || copy.features.testFlag(QStyleOptionButton::DefaultButton);
        copy.palette.setColor(QPalette::ButtonText,
                              enabled ? (emphasized ? VkStylePainter::contrastingText(colors.accent)
                                                    : colors.textPrimary)
                                      : colors.textDisabled);
        QProxyStyle::drawControl(element, &copy, painter, widget);
        return;
    }
    case CE_ComboBoxLabel: {
        const auto* combo = qstyleoption_cast<const QStyleOptionComboBox*>(option);
        const auto* comboWidget = qobject_cast<const QComboBox*>(widget);
        if (!combo || combo->editable || !comboWidget) {
            QProxyStyle::drawControl(element, option, painter, widget);
            return;
        }

        QRect textRect = subControlRect(CC_ComboBox, combo, SC_ComboBoxEditField, widget);
        painter->save();
        painter->setClipRect(textRect);
        if (!combo->currentIcon.isNull()) {
            const QSize requested = combo->iconSize.isValid() ? combo->iconSize : QSize(16, 16);
            const QSize actual = combo->currentIcon.actualSize(requested);
            const QRect iconRect = alignedRect(
                option->direction, Qt::AlignLeading | Qt::AlignVCenter, actual, textRect);
            combo->currentIcon.paint(painter, iconRect, Qt::AlignCenter,
                                     enabled ? QIcon::Normal : QIcon::Disabled);
            const int iconGap = qRound(metrics.spacing6);
            if (option->direction == Qt::LeftToRight) {
                textRect.setLeft(iconRect.right() + 1 + iconGap);
            } else {
                textRect.setRight(iconRect.left() - 1 - iconGap);
            }
        }

        const QString text = option->fontMetrics.elidedText(
            combo->currentText, comboBoxElideMode(*comboWidget), std::max(0, textRect.width()));
        painter->setPen(enabled ? colors.textPrimary : colors.textDisabled);
        painter->drawText(textRect, Qt::AlignLeading | Qt::AlignVCenter | Qt::TextSingleLine, text);
        painter->restore();
        return;
    }
    case CE_ProgressBarGroove:
        VkStylePainter::drawRoundedPanel(*painter, insetRect(option->rect, metrics.spacing4),
                                         metrics.cornerRadiusSmall, colors.controlFill,
                                         colors.border, metrics.borderWidth);
        return;
    case CE_ProgressBarContents: {
        const auto* progress = qstyleoption_cast<const QStyleOptionProgressBar*>(option);
        if (!progress || progress->maximum <= progress->minimum) {
            QProxyStyle::drawControl(element, option, painter, widget);
            return;
        }
        const qreal ratio = std::clamp(qreal(progress->progress - progress->minimum) /
                                           qreal(progress->maximum - progress->minimum),
                                       0.0, 1.0);
        QRectF groove = insetRect(option->rect, metrics.spacing4 + metrics.borderWidth);
        QRectF fill = groove;
        if (progress->state.testFlag(State_Horizontal)) {
            fill.setWidth(groove.width() * ratio);
            const bool reverse =
                progress->invertedAppearance != (option->direction == Qt::RightToLeft);
            if (reverse) {
                fill.moveRight(groove.right());
            }
        } else {
            fill.setHeight(groove.height() * ratio);
            if (!progress->invertedAppearance) {
                fill.moveBottom(groove.bottom());
            }
        }
        painter->save();
        painter->setRenderHint(QPainter::Antialiasing, true);
        painter->setClipPath(VkStylePainter::roundedRectPath(groove, metrics.cornerRadiusSmall));
        painter->fillRect(fill, enabled ? colors.accent : colors.controlFillDisabled);
        painter->restore();
        return;
    }
    case CE_ProgressBarLabel: {
        const auto* progress = qstyleoption_cast<const QStyleOptionProgressBar*>(option);
        if (!progress) {
            QProxyStyle::drawControl(element, option, painter, widget);
            return;
        }
        QStyleOptionProgressBar copy = *progress;
        copy.palette.setColor(QPalette::Text, enabled ? colors.textPrimary : colors.textDisabled);
        QProxyStyle::drawControl(element, &copy, painter, widget);
        return;
    }
    case CE_TabBarTabShape: {
        QColor fill = selected ? colors.elevatedBackground : Qt::transparent;
        if (!selected && hovered) {
            fill = colors.controlFillHovered;
        }
        VkStylePainter::drawRoundedPanel(
            *painter, insetRect(option->rect, metrics.spacing2), metrics.cornerRadiusRegular, fill,
            selected ? colors.border : Qt::transparent, selected ? metrics.borderWidth : 0.0);
        if (selected) {
            const QRectF indicator(option->rect.left() + metrics.spacing8,
                                   option->rect.bottom() -
                                       std::max<qreal>(2.0, metrics.borderWidth * 2.0),
                                   option->rect.width() - metrics.spacing16,
                                   std::max<qreal>(2.0, metrics.borderWidth * 2.0));
            painter->fillRect(indicator, colors.accent);
        }
        return;
    }
    case CE_TabBarTabLabel: {
        const auto* tab = qstyleoption_cast<const QStyleOptionTab*>(option);
        if (!tab) {
            QProxyStyle::drawControl(element, option, painter, widget);
            return;
        }
        QStyleOptionTab copy = *tab;
        copy.palette.setColor(QPalette::WindowText,
                              enabled ? (selected ? colors.textPrimary : colors.textSecondary)
                                      : colors.textDisabled);
        QProxyStyle::drawControl(element, &copy, painter, widget);
        return;
    }
    case CE_MenuItem: {
        const auto* menuItem = qstyleoption_cast<const QStyleOptionMenuItem*>(option);
        if (!menuItem) {
            break;
        }
        QStyleOptionMenuItem copy = *menuItem;
        if (selected && enabled) {
            VkStylePainter::drawRoundedPanel(*painter, insetRect(option->rect, metrics.spacing2),
                                             metrics.cornerRadiusSmall, colors.controlFillHovered,
                                             Qt::transparent, 0.0);
        }
        copy.state.setFlag(State_Selected, false);
        copy.palette.setColor(QPalette::Text, enabled ? colors.textPrimary : colors.textDisabled);
        copy.palette.setColor(QPalette::ButtonText,
                              enabled ? colors.textPrimary : colors.textDisabled);
        copy.palette.setColor(QPalette::Highlight, Qt::transparent);
        copy.palette.setColor(QPalette::HighlightedText,
                              enabled ? colors.textPrimary : colors.textDisabled);
        QProxyStyle::drawControl(element, &copy, painter, widget);
        return;
    }
    case CE_HeaderSection: {
        QColor fill = hovered ? colors.controlFillHovered : colors.controlFill;
        if (hasState(option, State_Sunken)) {
            fill = colors.controlFillPressed;
        }
        painter->fillRect(option->rect, fill);
        const qreal x =
            option->direction == Qt::LeftToRight ? option->rect.right() : option->rect.left();
        VkStylePainter::drawHairline(*painter, QPointF(x, option->rect.top() + metrics.spacing4),
                                     QPointF(x, option->rect.bottom() - metrics.spacing4),
                                     colors.separator);
        return;
    }
    case CE_HeaderLabel: {
        const auto* header = qstyleoption_cast<const QStyleOptionHeader*>(option);
        if (!header) {
            QProxyStyle::drawControl(element, option, painter, widget);
            return;
        }
        QStyleOptionHeader copy = *header;
        copy.palette.setColor(QPalette::ButtonText,
                              enabled ? colors.textSecondary : colors.textDisabled);
        QProxyStyle::drawControl(element, &copy, painter, widget);
        return;
    }
    case CE_ItemViewItem: {
        const auto* viewItem = qstyleoption_cast<const QStyleOptionViewItem*>(option);
        if (!viewItem) {
            break;
        }
        QStyleOptionViewItem copy = *viewItem;
        if (selected) {
            QColor selection = colors.accent;
            selection.setAlphaF(theme.effectiveAppearance() == VkAppearance::Dark ? 0.28F : 0.16F);
            VkStylePainter::drawRoundedPanel(*painter, insetRect(option->rect, metrics.spacing2),
                                             metrics.cornerRadiusSmall, selection, Qt::transparent,
                                             0.0);
        } else if (hovered) {
            if (d->popupSurfaces->isPopupPart(widget)) {
                VkStylePainter::drawRoundedPanel(
                    *painter, insetRect(option->rect, metrics.spacing2), metrics.cornerRadiusSmall,
                    colors.controlFillHovered, Qt::transparent, 0.0);
            } else {
                painter->fillRect(option->rect, colors.controlFillHovered);
            }
        }
        copy.state.setFlag(State_Selected, false);
        copy.state.setFlag(State_MouseOver, false);
        copy.palette.setColor(QPalette::Text, enabled ? colors.textPrimary : colors.textDisabled);
        copy.palette.setColor(QPalette::HighlightedText,
                              enabled ? colors.textPrimary : colors.textDisabled);
        QProxyStyle::drawControl(element, &copy, painter, widget);
        return;
    }
    default:
        QProxyStyle::drawControl(element, option, painter, widget);
        return;
    }

    QProxyStyle::drawControl(element, option, painter, widget);
}

void VkStyle::drawComplexControl(ComplexControl control, const QStyleOptionComplex* option,
                                 QPainter* painter, const QWidget* widget) const {
    if (!option || !painter) {
        return;
    }

    const VkTheme& theme = VkThemeManager::instance()->theme();
    const auto& colors = theme.colors();
    const auto& metrics = theme.metrics();
    const bool enabled = hasState(option, State_Enabled);
    const bool hovered = hasState(option, State_MouseOver);
    const bool pressed = hasState(option, State_Sunken);
    const bool focused = hasState(option, State_HasFocus);
    const bool selected = hasState(option, State_On);
    const auto progress =
        d->animations->progress(const_cast<QWidget*>(widget), hovered, pressed, focused, selected);

    switch (control) {
    case CC_ToolButton: {
        const auto* toolButton = qstyleoption_cast<const QStyleOptionToolButton*>(option);
        if (!toolButton) {
            break;
        }
        drawPrimitive(PE_PanelButtonTool, toolButton, painter, widget);
        QStyleOptionToolButton label = *toolButton;
        label.palette.setColor(QPalette::ButtonText,
                               enabled ? colors.textPrimary : colors.textDisabled);
        drawControl(CE_ToolButtonLabel, &label, painter, widget);
        if (toolButton->features.testFlag(QStyleOptionToolButton::MenuButtonPopup) ||
            toolButton->features.testFlag(QStyleOptionToolButton::HasMenu)) {
            const QRect arrowRect =
                subControlRect(CC_ToolButton, toolButton, SC_ToolButtonMenu, widget);
            VkStylePainter::drawChevron(*painter, QRectF(arrowRect), Qt::DownArrow,
                                        enabled ? colors.symbolSecondary : colors.symbolDisabled,
                                        std::max<qreal>(1.25, metrics.borderWidth * 1.5));
        }
        return;
    }
    case CC_ComboBox: {
        const auto* combo = qstyleoption_cast<const QStyleOptionComboBox*>(option);
        if (!combo) {
            break;
        }
        QColor fill = combo->editable ? colors.contentBackground : colors.controlFill;
        fill = VkStylePainter::mix(fill, colors.controlFillHovered, progress.hover);
        fill = VkStylePainter::mix(fill, colors.controlFillPressed, progress.press);
        if (!enabled) {
            fill = colors.controlFillDisabled;
        }
        VkStylePainter::drawRoundedPanel(
            *painter, QRectF(option->rect), metrics.cornerRadiusRegular, fill,
            VkStylePainter::mix(colors.border, colors.borderStrong, progress.focus),
            metrics.borderWidth);
        const QRect arrowRect = subControlRect(CC_ComboBox, combo, SC_ComboBoxArrow, widget);
        const QRectF glyphColumn =
            QRectF(arrowRect).adjusted(metrics.spacing6, 0.0, -metrics.spacing6, 0.0);
        const QRectF upChevron(glyphColumn.left(), glyphColumn.center().y() - 8.0,
                               glyphColumn.width(), 10.0);
        const QRectF downChevron(glyphColumn.left(), glyphColumn.center().y() - 2.0,
                                 glyphColumn.width(), 10.0);
        const QColor symbol = enabled ? colors.symbolSecondary : colors.symbolDisabled;
        const qreal chevronWidth = std::max<qreal>(1.1, metrics.borderWidth * 1.35);
        VkStylePainter::drawChevron(*painter, upChevron, Qt::UpArrow, symbol, chevronWidth);
        VkStylePainter::drawChevron(*painter, downChevron, Qt::DownArrow, symbol, chevronWidth);
        if (progress.focus > 0.0) {
            VkStylePainter::drawFocusRing(
                *painter, insetRect(option->rect, metrics.spacing2), metrics.cornerRadiusRegular,
                VkStylePainter::multiplyAlpha(
                    VkStylePainter::neutralFocusColor(colors.borderStrong), progress.focus),
                std::max<qreal>(1.0, metrics.borderWidth));
        }
        return;
    }
    case CC_SpinBox: {
        const auto* spinBox = qstyleoption_cast<const QStyleOptionSpinBox*>(option);
        if (!spinBox) {
            break;
        }
        QColor fill = VkStylePainter::mix(colors.contentBackground, colors.controlFillHovered,
                                          progress.hover * 0.5);
        if (!enabled) {
            fill = colors.controlFillDisabled;
        }
        VkStylePainter::drawRoundedPanel(
            *painter, QRectF(option->rect), metrics.cornerRadiusRegular, fill,
            VkStylePainter::mix(colors.border, colors.borderStrong, progress.focus),
            metrics.borderWidth);
        const QRect upRect = subControlRect(CC_SpinBox, spinBox, SC_SpinBoxUp, widget);
        const QRect downRect = subControlRect(CC_SpinBox, spinBox, SC_SpinBoxDown, widget);
        VkStylePainter::drawChevron(*painter, QRectF(upRect), Qt::UpArrow,
                                    enabled ? colors.symbolSecondary : colors.symbolDisabled,
                                    std::max<qreal>(1.0, metrics.borderWidth * 1.35));
        VkStylePainter::drawChevron(*painter, QRectF(downRect), Qt::DownArrow,
                                    enabled ? colors.symbolSecondary : colors.symbolDisabled,
                                    std::max<qreal>(1.0, metrics.borderWidth * 1.35));
        const qreal buttonBoundary =
            option->direction == Qt::LeftToRight ? upRect.left() : upRect.right();
        VkStylePainter::drawHairline(
            *painter, QPointF(buttonBoundary, option->rect.top() + metrics.spacing4),
            QPointF(buttonBoundary, option->rect.bottom() - metrics.spacing4), colors.separator);
        if (progress.focus > 0.0) {
            VkStylePainter::drawFocusRing(
                *painter, insetRect(option->rect, metrics.spacing2), metrics.cornerRadiusRegular,
                VkStylePainter::multiplyAlpha(
                    VkStylePainter::neutralFocusColor(colors.borderStrong), progress.focus),
                std::max<qreal>(1.0, metrics.borderWidth));
        }
        return;
    }
    case CC_Slider: {
        const auto* slider = qstyleoption_cast<const QStyleOptionSlider*>(option);
        if (!slider) {
            break;
        }
        const QRectF groove = subControlRect(CC_Slider, slider, SC_SliderGroove, widget);
        QRectF active = groove;
        const QRectF handle = subControlRect(CC_Slider, slider, SC_SliderHandle, widget);
        if (slider->orientation == Qt::Horizontal) {
            if (slider->upsideDown) {
                active.setLeft(handle.center().x());
            } else {
                active.setRight(handle.center().x());
            }
        } else if (slider->upsideDown) {
            active.setTop(handle.center().y());
        } else {
            active.setBottom(handle.center().y());
        }
        VkStylePainter::drawRoundedPanel(*painter, groove,
                                         std::min(groove.width(), groove.height()) * 0.5,
                                         colors.controlFill, Qt::transparent, 0.0);
        VkStylePainter::drawRoundedPanel(
            *painter, active, std::min(active.width(), active.height()) * 0.5,
            enabled ? colors.accent : colors.controlFillDisabled, Qt::transparent, 0.0);
        const qreal expansion = progress.hover * 1.0 + progress.press * 0.5;
        const QRectF drawnHandle = handle.adjusted(-expansion, -expansion, expansion, expansion);
        VkStylePainter::drawRoundedPanel(
            *painter, drawnHandle, std::min(drawnHandle.width(), drawnHandle.height()) * 0.5,
            enabled ? colors.elevatedBackground : colors.controlFillDisabled, colors.borderStrong,
            metrics.borderWidth);
        if (progress.focus > 0.0) {
            VkStylePainter::drawFocusRing(
                *painter,
                drawnHandle.adjusted(-metrics.spacing2, -metrics.spacing2, metrics.spacing2,
                                     metrics.spacing2),
                std::min(drawnHandle.width(), drawnHandle.height()) * 0.5 + metrics.spacing2,
                VkStylePainter::multiplyAlpha(
                    VkStylePainter::neutralFocusColor(colors.borderStrong), progress.focus),
                std::max<qreal>(1.0, metrics.borderWidth));
        }
        return;
    }
    case CC_ScrollBar: {
        const auto* scrollBar = qstyleoption_cast<const QStyleOptionSlider*>(option);
        if (!scrollBar) {
            break;
        }
        const QRect groove = subControlRect(CC_ScrollBar, scrollBar, SC_ScrollBarGroove, widget);
        const QRect slider = subControlRect(CC_ScrollBar, scrollBar, SC_ScrollBarSlider, widget);
        painter->fillRect(groove, VkStylePainter::multiplyAlpha(colors.controlFill, 0.45));
        const qreal inset = progress.hover > 0.0 ? metrics.spacing2 : metrics.spacing4;
        const QRectF thumb = scrollBar->orientation == Qt::Horizontal
                                 ? QRectF(slider).adjusted(0.0, inset, 0.0, -inset)
                                 : QRectF(slider).adjusted(inset, 0.0, -inset, 0.0);
        QColor thumbColor =
            VkStylePainter::mix(colors.borderStrong, colors.textTertiary, progress.hover);
        if (progress.press > 0.0) {
            thumbColor = VkStylePainter::mix(thumbColor, colors.textSecondary, progress.press);
        }
        VkStylePainter::drawRoundedPanel(
            *painter, thumb, std::min(thumb.width(), thumb.height()) * 0.5,
            enabled ? thumbColor : colors.controlFillDisabled, Qt::transparent, 0.0);
        return;
    }
    default:
        QProxyStyle::drawComplexControl(control, option, painter, widget);
        return;
    }

    QProxyStyle::drawComplexControl(control, option, painter, widget);
}

int VkStyle::pixelMetric(PixelMetric metric, const QStyleOption* option,
                         const QWidget* widget) const {
    const auto& tokens = VkThemeManager::instance()->theme().metrics();
    switch (metric) {
    case PM_DefaultFrameWidth:
    case PM_ComboBoxFrameWidth:
    case PM_SpinBoxFrameWidth:
    case PM_MenuPanelWidth:
        return std::max(1, qRound(tokens.borderWidth));
    case PM_ButtonMargin:
        return qRound(tokens.spacing8);
    case PM_ButtonDefaultIndicator:
        return 0;
    case PM_ButtonIconSize:
    case PM_SmallIconSize:
        return qRound(tokens.controlHeightSmall * 0.67);
    case PM_LargeIconSize:
        return qRound(tokens.controlHeightRegular * 0.86);
    case PM_IndicatorWidth:
    case PM_IndicatorHeight:
    case PM_ExclusiveIndicatorWidth:
    case PM_ExclusiveIndicatorHeight:
        return widget ? vkui::controlExtent(*widget) : vkui::controlExtent(VkControlSize::Regular);
    case PM_LayoutLeftMargin:
    case PM_LayoutTopMargin:
    case PM_LayoutRightMargin:
    case PM_LayoutBottomMargin:
        return qRound(tokens.spacing12);
    case PM_LayoutHorizontalSpacing:
    case PM_LayoutVerticalSpacing:
        return qRound(tokens.spacing8);
    case PM_ScrollBarExtent:
        return qRound(tokens.controlHeightSmall * 0.58);
    case PM_ScrollBarSliderMin:
        return qRound(tokens.spacing24);
    case PM_SliderThickness:
        return qRound(tokens.controlHeightSmall);
    case PM_SliderLength:
        return qRound(tokens.controlHeightSmall * 0.72);
    case PM_ProgressBarChunkWidth:
        return qRound(tokens.spacing8);
    case PM_TabBarTabHSpace:
        return qRound(tokens.spacing16);
    case PM_TabBarTabVSpace:
        return qRound(tokens.spacing8);
    case PM_MenuHMargin:
    case PM_MenuVMargin:
        return qRound(tokens.spacing6);
    case PM_MenuButtonIndicator:
        return qRound(tokens.controlHeightSmall * 0.60);
    case PM_HeaderMargin:
        return qRound(tokens.spacing8);
    case PM_FocusFrameHMargin:
    case PM_FocusFrameVMargin:
        return qRound(tokens.spacing2 + std::max<qreal>(1.0, tokens.borderWidth));
    default:
        return QProxyStyle::pixelMetric(metric, option, widget);
    }
}

int VkStyle::layoutSpacing(QSizePolicy::ControlType control1, QSizePolicy::ControlType control2,
                           Qt::Orientation orientation, const QStyleOption* option,
                           const QWidget* widget) const {
    Q_UNUSED(control1)
    Q_UNUSED(control2)
    Q_UNUSED(orientation)
    Q_UNUSED(option)
    Q_UNUSED(widget)
    return qRound(VkThemeManager::instance()->theme().metrics().spacing8);
}

QSize VkStyle::sizeFromContents(ContentsType type, const QStyleOption* option,
                                const QSize& contentsSize, const QWidget* widget) const {
    QSize result = QProxyStyle::sizeFromContents(type, option, contentsSize, widget);
    const auto& metrics = VkThemeManager::instance()->theme().metrics();
    switch (type) {
    case CT_PushButton:
        result.rwidth() =
            std::max(result.width(), contentsSize.width() + qRound(metrics.spacing24));
        result.rheight() = std::max(result.height(), qRound(metrics.controlHeightRegular));
        break;
    case CT_ToolButton:
        result = result.expandedTo(
            QSize(qRound(metrics.controlHeightRegular), qRound(metrics.controlHeightRegular)));
        break;
    case CT_LineEdit:
        result.rheight() = std::max(result.height(), qRound(metrics.controlHeightRegular));
        result.rwidth() =
            std::max(result.width(), contentsSize.width() + qRound(metrics.spacing16));
        break;
    case CT_ComboBox:
        result.rheight() = std::max(result.height(), qRound(metrics.controlHeightRegular));
        result.rwidth() =
            std::max(result.width(), contentsSize.width() +
                                         qRound(metrics.controlHeightRegular + metrics.spacing20));
        break;
    case CT_SpinBox:
        result.rheight() = std::max(result.height(), qRound(metrics.controlHeightRegular));
        result.rwidth() = std::max(
            result.width(),
            contentsSize.width() + qRound(metrics.controlHeightRegular * 0.78 + metrics.spacing20));
        break;
    case CT_CheckBox:
    case CT_RadioButton:
        result.rheight() =
            std::max(result.height(), (widget ? vkui::controlExtent(*widget)
                                              : vkui::controlExtent(VkControlSize::Regular)) +
                                          qRound(metrics.spacing8));
        break;
    case CT_ProgressBar:
        result.rheight() = std::max(result.height(), qRound(metrics.controlHeightSmall));
        break;
    case CT_TabBarTab:
        result.rheight() = std::max(result.height(), qRound(metrics.controlHeightRegular));
        result.rwidth() =
            std::max(result.width(), contentsSize.width() + qRound(metrics.spacing16));
        break;
    case CT_MenuItem:
        result.rheight() = std::max(result.height(), qRound(metrics.controlHeightRegular));
        result.rwidth() += qRound(metrics.spacing8);
        break;
    default:
        break;
    }
    return result;
}

QRect VkStyle::subElementRect(SubElement element, const QStyleOption* option,
                              const QWidget* widget) const {
    if (!option) {
        return {};
    }
    const auto& metrics = VkThemeManager::instance()->theme().metrics();
    switch (element) {
    case SE_PushButtonContents:
        return option->rect.adjusted(qRound(metrics.spacing12), qRound(metrics.spacing4),
                                     -qRound(metrics.spacing12), -qRound(metrics.spacing4));
    case SE_LineEditContents:
        return option->rect.adjusted(qRound(metrics.spacing8), qRound(metrics.spacing4),
                                     -qRound(metrics.spacing8), -qRound(metrics.spacing4));
    case SE_CheckBoxIndicator:
    case SE_RadioButtonIndicator: {
        const int extent = pixelMetric(element == SE_CheckBoxIndicator ? PM_IndicatorWidth
                                                                       : PM_ExclusiveIndicatorWidth,
                                       option, widget);
        const QRect logical(option->rect.left(), option->rect.center().y() - extent / 2, extent,
                            extent);
        return visualRect(option->direction, option->rect, logical);
    }
    case SE_CheckBoxContents:
    case SE_RadioButtonContents: {
        const bool checkBox = element == SE_CheckBoxContents;
        const int extent =
            pixelMetric(checkBox ? PM_IndicatorWidth : PM_ExclusiveIndicatorWidth, option, widget);
        const int gap = qRound(metrics.spacing6);
        const QRect logical(option->rect.left() + extent + gap, option->rect.top(),
                            std::max(0, option->rect.width() - extent - gap),
                            option->rect.height());
        return visualRect(option->direction, option->rect, logical);
    }
    case SE_CheckBoxFocusRect:
    case SE_RadioButtonFocusRect:
        return option->rect;
    case SE_FrameContents:
        return option->rect.adjusted(qRound(metrics.borderWidth), qRound(metrics.borderWidth),
                                     -qRound(metrics.borderWidth), -qRound(metrics.borderWidth));
    default:
        return QProxyStyle::subElementRect(element, option, widget);
    }
}

QRect VkStyle::subControlRect(ComplexControl control, const QStyleOptionComplex* option,
                              SubControl subControl, const QWidget* widget) const {
    if (!option) {
        return {};
    }
    const auto& metrics = VkThemeManager::instance()->theme().metrics();
    switch (control) {
    case CC_ComboBox: {
        const int arrowWidth = qRound(metrics.controlHeightRegular);
        const QRect logicalArrow(option->rect.right() - arrowWidth + 1, option->rect.top(),
                                 arrowWidth, option->rect.height());
        const QRect arrow = visualRect(option->direction, option->rect, logicalArrow);
        if (subControl == SC_ComboBoxArrow) {
            return arrow;
        }
        if (subControl == SC_ComboBoxEditField) {
            const QRect logical(
                option->rect.left() + qRound(metrics.spacing8),
                option->rect.top() + qRound(metrics.borderWidth),
                std::max(0, option->rect.width() - arrowWidth - qRound(metrics.spacing12)),
                option->rect.height() - qRound(metrics.borderWidth * 2.0));
            return visualRect(option->direction, option->rect, logical);
        }
        break;
    }
    case CC_SpinBox: {
        const int buttonWidth = qRound(metrics.controlHeightRegular * 0.78);
        const QRect logicalButtons(option->rect.right() - buttonWidth + 1, option->rect.top(),
                                   buttonWidth, option->rect.height());
        const QRect buttons = visualRect(option->direction, option->rect, logicalButtons);
        if (subControl == SC_SpinBoxUp) {
            return QRect(buttons.left(), buttons.top(), buttons.width(), buttons.height() / 2);
        }
        if (subControl == SC_SpinBoxDown) {
            return QRect(buttons.left(), buttons.top() + buttons.height() / 2, buttons.width(),
                         buttons.height() - buttons.height() / 2);
        }
        if (subControl == SC_SpinBoxEditField) {
            const QRect logical(
                option->rect.left() + qRound(metrics.spacing8),
                option->rect.top() + qRound(metrics.borderWidth),
                std::max(0, option->rect.width() - buttonWidth - qRound(metrics.spacing12)),
                option->rect.height() - qRound(metrics.borderWidth * 2.0));
            return visualRect(option->direction, option->rect, logical);
        }
        break;
    }
    case CC_Slider: {
        const auto* slider = qstyleoption_cast<const QStyleOptionSlider*>(option);
        if (!slider) {
            break;
        }
        const int handleExtent = pixelMetric(PM_SliderLength, slider, widget);
        const int grooveExtent = std::max(4, qRound(metrics.spacing4));
        if (subControl == SC_SliderGroove) {
            if (slider->orientation == Qt::Horizontal) {
                return QRect(option->rect.left() + handleExtent / 2,
                             option->rect.center().y() - grooveExtent / 2,
                             std::max(0, option->rect.width() - handleExtent), grooveExtent);
            }
            return QRect(option->rect.center().x() - grooveExtent / 2,
                         option->rect.top() + handleExtent / 2, grooveExtent,
                         std::max(0, option->rect.height() - handleExtent));
        }
        if (subControl == SC_SliderHandle) {
            const int span = (slider->orientation == Qt::Horizontal ? option->rect.width()
                                                                    : option->rect.height()) -
                             handleExtent;
            const int position = QStyle::sliderPositionFromValue(
                slider->minimum, slider->maximum, slider->sliderPosition, std::max(0, span),
                slider->upsideDown);
            if (slider->orientation == Qt::Horizontal) {
                return QRect(option->rect.left() + position,
                             option->rect.center().y() - handleExtent / 2, handleExtent,
                             handleExtent);
            }
            return QRect(option->rect.center().x() - handleExtent / 2,
                         option->rect.top() + position, handleExtent, handleExtent);
        }
        break;
    }
    default:
        break;
    }
    return QProxyStyle::subControlRect(control, option, subControl, widget);
}

QStyle::SubControl VkStyle::hitTestComplexControl(ComplexControl control,
                                                  const QStyleOptionComplex* option,
                                                  const QPoint& position,
                                                  const QWidget* widget) const {
    if (!option) {
        return SC_None;
    }
    const auto controlsFor = [control]() {
        switch (control) {
        case CC_ComboBox:
            return std::array{SC_ComboBoxArrow, SC_ComboBoxEditField, SC_None, SC_None};
        case CC_SpinBox:
            return std::array{SC_SpinBoxUp, SC_SpinBoxDown, SC_SpinBoxEditField, SC_None};
        case CC_Slider:
            return std::array{SC_SliderHandle, SC_SliderGroove, SC_None, SC_None};
        default:
            return std::array{SC_None, SC_None, SC_None, SC_None};
        }
    }();
    for (SubControl subControl : controlsFor) {
        if (subControl != SC_None && option->subControls.testFlag(subControl) &&
            subControlRect(control, option, subControl, widget).contains(position)) {
            return subControl;
        }
    }
    return QProxyStyle::hitTestComplexControl(control, option, position, widget);
}

int VkStyle::styleHint(StyleHint hint, const QStyleOption* option, const QWidget* widget,
                       QStyleHintReturn* returnData) const {
    switch (hint) {
    case SH_Widget_Animate:
        return VkThemeManager::instance()->animationsEnabled() ? 1 : 0;
    case SH_EtchDisabledText:
    case SH_DitherDisabledText:
        return 0;
    case SH_ItemView_ShowDecorationSelected:
        return 1;
    default:
        return QProxyStyle::styleHint(hint, option, widget, returnData);
    }
}

QIcon VkStyle::standardIcon(StandardPixmap standardIcon, const QStyleOption* option,
                            const QWidget* widget) const {
    const Qt::LayoutDirection direction =
        option ? option->direction : (widget ? widget->layoutDirection() : Qt::LeftToRight);
    switch (standardIcon) {
    case SP_ArrowLeft:
        return icon(VkSymbol::ChevronLeft);
    case SP_ArrowRight:
        return icon(VkSymbol::ChevronRight);
    case SP_ArrowUp:
        return icon(VkSymbol::ChevronUp);
    case SP_ArrowDown:
        return icon(VkSymbol::ChevronDown);
    case SP_ArrowBack:
        return icon(direction == Qt::RightToLeft ? VkSymbol::ChevronRight : VkSymbol::ChevronLeft);
    case SP_ArrowForward:
        return icon(direction == Qt::RightToLeft ? VkSymbol::ChevronLeft : VkSymbol::ChevronRight);
    case SP_TitleBarCloseButton:
    case SP_DialogCloseButton:
    case SP_DialogCancelButton:
        return icon(VkSymbol::Close);
    case SP_DialogApplyButton:
    case SP_DialogYesButton:
        return icon(VkSymbol::Checkmark, VkIconRole::Accent);
    case SP_FileIcon:
        return icon(VkSymbol::Document);
    case SP_DirIcon:
    case SP_DirOpenIcon:
        return icon(VkSymbol::Folder);
    case SP_MessageBoxInformation:
        return icon(VkSymbol::Information, VkIconRole::Accent);
    case SP_MessageBoxWarning:
        return icon(VkSymbol::Warning);
    default:
        return QProxyStyle::standardIcon(standardIcon, option, widget);
    }
}

QPalette VkStyle::standardPalette() const {
    const auto& colors = VkThemeManager::instance()->theme().colors();
    QPalette palette;
    palette.setColor(QPalette::Window, colors.windowBackground);
    palette.setColor(QPalette::WindowText, colors.textPrimary);
    palette.setColor(QPalette::Base, colors.contentBackground);
    palette.setColor(QPalette::AlternateBase, colors.elevatedBackground);
    palette.setColor(QPalette::ToolTipBase, colors.elevatedBackground);
    palette.setColor(QPalette::ToolTipText, colors.textPrimary);
    palette.setColor(QPalette::Text, colors.textPrimary);
    palette.setColor(QPalette::Button, colors.controlFill);
    palette.setColor(QPalette::ButtonText, colors.textPrimary);
    palette.setColor(QPalette::BrightText, colors.destructive);
    palette.setColor(QPalette::Light, colors.elevatedBackground);
    palette.setColor(QPalette::Midlight, colors.separator);
    palette.setColor(QPalette::Dark, colors.borderStrong);
    palette.setColor(QPalette::Mid, colors.border);
    palette.setColor(QPalette::Shadow, colors.shadow);
    palette.setColor(QPalette::Highlight, colors.accent);
    palette.setColor(QPalette::HighlightedText, VkStylePainter::contrastingText(colors.accent));
    palette.setColor(QPalette::Link, colors.accent);
    palette.setColor(QPalette::LinkVisited, colors.accentPressed);
    palette.setColor(QPalette::PlaceholderText, colors.textTertiary);
    palette.setColor(QPalette::Accent, colors.accent);

    palette.setColor(QPalette::Inactive, QPalette::Highlight, colors.accentHovered);
    palette.setColor(QPalette::Inactive, QPalette::HighlightedText,
                     VkStylePainter::contrastingText(colors.accentHovered));
    palette.setColor(QPalette::Disabled, QPalette::WindowText, colors.textDisabled);
    palette.setColor(QPalette::Disabled, QPalette::Text, colors.textDisabled);
    palette.setColor(QPalette::Disabled, QPalette::Button, colors.controlFillDisabled);
    palette.setColor(QPalette::Disabled, QPalette::ButtonText, colors.textDisabled);
    palette.setColor(QPalette::Disabled, QPalette::BrightText, colors.textDisabled);
    palette.setColor(QPalette::Disabled, QPalette::Highlight, colors.controlFillDisabled);
    palette.setColor(QPalette::Disabled, QPalette::HighlightedText, colors.textDisabled);
    palette.setColor(QPalette::Disabled, QPalette::Link, colors.textDisabled);
    palette.setColor(QPalette::Disabled, QPalette::LinkVisited, colors.textDisabled);
    palette.setColor(QPalette::Disabled, QPalette::PlaceholderText, colors.textDisabled);
    palette.setColor(QPalette::Disabled, QPalette::Accent, colors.textDisabled);
    return palette;
}

void VkStyle::polish(QPalette& palette) {
    QProxyStyle::polish(palette);
    palette = standardPalette();
}

void VkStyle::polish(QApplication* application) {
    QProxyStyle::polish(application);
}

void VkStyle::polish(QWidget* widget) {
    QProxyStyle::polish(widget);
    d->popupSurfaces->polish(widget);
    if (VkStylePrivate::supportsAnimations(widget)) {
        d->animations->watch(widget);
    }
}

void VkStyle::unpolish(QApplication* application) {
    QProxyStyle::unpolish(application);
}

void VkStyle::unpolish(QWidget* widget) {
    d->animations->unwatch(widget);
    d->popupSurfaces->unpolish(widget);
    QProxyStyle::unpolish(widget);
}

void installVkUi(QApplication& application) {
    static std::once_flag resourcesOnce;
    std::call_once(resourcesOnce, initializeVkUiResources);

    // Creating the manager resolves Auto appearance and installs system-change listeners.
    auto* const themeManager = VkThemeManager::instance();
    Q_UNUSED(themeManager)
    if (!qobject_cast<VkStyle*>(application.style())) {
        application.setStyle(new VkStyle);
    }

    constexpr auto synchronizerName = "_vkui_runtime_theme_synchronizer";
    if (!application.findChild<QObject*>(QString::fromLatin1(synchronizerName),
                                         Qt::FindDirectChildrenOnly)) {
        auto* synchronizer = new VkRuntimeThemeSynchronizer(application);
        synchronizer->setObjectName(QString::fromLatin1(synchronizerName));
    }
}

} // namespace vkui
