# SPDX-License-Identifier: MIT

include_guard(GLOBAL)

function(_vkui_write_if_different path content)
    get_filename_component(directory "${path}" DIRECTORY)
    file(MAKE_DIRECTORY "${directory}")
    if(EXISTS "${path}")
        file(READ "${path}" existing)
        if("${existing}" STREQUAL "${content}")
            return()
        endif()
    endif()
    file(WRITE "${path}" "${content}")
endfunction()

function(vkui_generate_icon_catalog)
    set(one_value_arguments MANIFEST ICON_DIR OUTPUT_DIR)
    cmake_parse_arguments(PARSE_ARGV 0 ARG "" "${one_value_arguments}" "")
    foreach(required IN LISTS one_value_arguments)
        if(NOT ARG_${required})
            message(FATAL_ERROR "vkui_generate_icon_catalog requires ${required}")
        endif()
    endforeach()

    get_filename_component(manifest "${ARG_MANIFEST}" ABSOLUTE)
    get_filename_component(icon_dir "${ARG_ICON_DIR}" ABSOLUTE)
    get_filename_component(output_dir "${ARG_OUTPUT_DIR}" ABSOLUTE)
    if(NOT EXISTS "${manifest}")
        message(FATAL_ERROR "VkUI icon manifest does not exist: ${manifest}")
    endif()

    file(READ "${manifest}" manifest_json)
    string(JSON root_type TYPE "${manifest_json}")
    if(NOT root_type STREQUAL "OBJECT")
        message(FATAL_ERROR "VkUI icon manifest root must be an object")
    endif()
    string(JSON root_member_count LENGTH "${manifest_json}")
    math(EXPR last_root_member "${root_member_count} - 1")
    set(allowed_root_members formatVersion symbols)
    foreach(member_index RANGE 0 ${last_root_member})
        string(JSON member_name MEMBER "${manifest_json}" ${member_index})
        if(NOT member_name IN_LIST allowed_root_members)
            message(FATAL_ERROR
                "Unnecessary or unsupported VkUI icon manifest field '${member_name}'")
        endif()
    endforeach()
    string(JSON format_version GET "${manifest_json}" formatVersion)
    if(NOT format_version EQUAL 1)
        message(FATAL_ERROR "Unsupported VkUI icon manifest version: ${format_version}")
    endif()
    string(JSON symbols_type TYPE "${manifest_json}" symbols)
    if(NOT symbols_type STREQUAL "ARRAY")
        message(FATAL_ERROR "VkUI icon manifest 'symbols' field must be an array")
    endif()
    string(JSON symbol_count LENGTH "${manifest_json}" symbols)
    if(symbol_count LESS 1)
        message(FATAL_ERROR "VkUI icon manifest must contain at least one symbol")
    endif()

    set(enum_entries "")
    set(registry_entries "")
    set(qrc_entries "")
    set(chosen_entries "")
    set(symbol_ids "")
    set(symbol_assets "")
    set(chosen_count 0)
    math(EXPR last_symbol "${symbol_count} - 1")
    foreach(index RANGE 0 ${last_symbol})
        string(JSON id GET "${manifest_json}" symbols ${index} id)
        string(JSON asset GET "${manifest_json}" symbols ${index} asset)
        if(NOT id MATCHES "^[A-Z][A-Za-z0-9]*$")
            message(FATAL_ERROR "Invalid VkSymbol identifier at index ${index}: ${id}")
        endif()
        if(NOT asset MATCHES "^[a-z0-9][a-z0-9-]*\\.svg$")
            message(FATAL_ERROR "Invalid VkUI icon asset at index ${index}: ${asset}")
        endif()
        if(id IN_LIST symbol_ids)
            message(FATAL_ERROR "Duplicate VkSymbol identifier: ${id}")
        endif()
        if(asset IN_LIST symbol_assets)
            message(FATAL_ERROR "Duplicate VkUI icon asset: ${asset}")
        endif()
        set(asset_path "${icon_dir}/${asset}")
        if(NOT EXISTS "${asset_path}")
            message(FATAL_ERROR "VkUI icon asset does not exist: ${asset_path}")
        endif()

        # The renderer encodes these two semantic colors into a reusable geometry mask.
        # Reject arbitrary literal colors so a new asset cannot silently bypass theming.
        file(READ "${asset_path}" asset_source)
        if(NOT asset_source MATCHES "#000001")
            message(FATAL_ERROR "VkUI icon asset must contain the primary #000001 token: ${asset}")
        endif()
        string(REGEX MATCHALL "#[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]"
            color_literals "${asset_source}")
        foreach(color IN LISTS color_literals)
            if(NOT color STREQUAL "#000001" AND NOT color STREQUAL "#000002")
                message(FATAL_ERROR
                    "VkUI icon asset contains unsupported literal color '${color}': ${asset}")
            endif()
        endforeach()

        string(JSON member_count LENGTH "${manifest_json}" symbols ${index})
        math(EXPR last_member "${member_count} - 1")
        set(allowed_members id asset collection label sourceName)
        foreach(member_index RANGE 0 ${last_member})
            string(JSON member_name MEMBER "${manifest_json}" symbols ${index} ${member_index})
            if(NOT member_name IN_LIST allowed_members)
                message(FATAL_ERROR
                    "Unnecessary or unsupported field '${member_name}' in VkSymbol ${id}")
            endif()
        endforeach()

        set(collection "")
        string(JSON parsed_collection ERROR_VARIABLE collection_error
            GET "${manifest_json}" symbols ${index} collection)
        if(collection_error STREQUAL "NOTFOUND")
            set(collection "${parsed_collection}")
        endif()
        if(collection)
            if(NOT collection STREQUAL "chosen")
                message(FATAL_ERROR "Unsupported VkUI icon collection '${collection}' for ${id}")
            endif()
            string(JSON label GET "${manifest_json}" symbols ${index} label)
            string(JSON source_name GET "${manifest_json}" symbols ${index} sourceName)
            if(label STREQUAL "" OR source_name STREQUAL "")
                message(FATAL_ERROR "Chosen VkSymbol ${id} requires label and sourceName")
            endif()
            if(NOT label MATCHES "^[A-Za-z0-9][A-Za-z0-9 -]*$")
                message(FATAL_ERROR "Invalid chosen label for ${id}: ${label}")
            endif()
            if(NOT source_name MATCHES "^[a-z0-9_-]+$")
                message(FATAL_ERROR "Invalid chosen sourceName for ${id}: ${source_name}")
            endif()
            string(APPEND chosen_entries
                "    {vkui::VkSymbol::${id}, \"${label}\", \"${source_name}\"},\n")
            math(EXPR chosen_count "${chosen_count} + 1")
        elseif(NOT member_count EQUAL 2)
            message(FATAL_ERROR
                "VkSymbol ${id} may only contain id and asset unless it belongs to a collection")
        endif()

        list(APPEND symbol_ids "${id}")
        list(APPEND symbol_assets "${asset}")
        string(APPEND enum_entries "    ${id},\n")
        string(APPEND registry_entries "    \"${asset}\",\n")
        string(APPEND qrc_entries
            "        <file alias=\"${asset}\">${icon_dir}/${asset}</file>\n")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${icon_dir}/${asset}")
    endforeach()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${manifest}")

    # Keep the directory and manifest bijective: an unregistered SVG is dead data and an easy
    # source of licensing or packaging drift.
    file(GLOB directory_assets CONFIGURE_DEPENDS RELATIVE "${icon_dir}" "${icon_dir}/*.svg")
    set(unregistered_assets ${directory_assets})
    list(REMOVE_ITEM unregistered_assets ${symbol_assets})
    if(unregistered_assets)
        list(JOIN unregistered_assets ", " unregistered_text)
        message(FATAL_ERROR "Unregistered VkUI SVG assets: ${unregistered_text}")
    endif()

    set(symbol_header "${output_dir}/include/vkui/core/VkSymbol.h")
    set(registry_header "${output_dir}/private/VkSymbolRegistry_p.h")
    set(chosen_header "${output_dir}/gallery/VkChosenSymbols_p.h")
    set(icon_qrc "${output_dir}/resources/vkui.qrc")

    set(symbol_header_content "// SPDX-License-Identifier: MIT\n\n#pragma once\n\nnamespace vkui {\n\nenum class VkSymbol {\n${enum_entries}    Count,\n};\n\n} // namespace vkui\n")
    set(registry_header_content "// SPDX-License-Identifier: MIT\n\n#pragma once\n\n#include <array>\n#include <string_view>\n#include <vkui/core/VkSymbol.h>\n\nnamespace vkui::detail {\n\ninline constexpr std::array<std::string_view, static_cast<std::size_t>(VkSymbol::Count)>\n    kVkSymbolAssets{{\n${registry_entries}}};\n\n} // namespace vkui::detail\n")
    set(chosen_header_content "// SPDX-License-Identifier: MIT\n\n#pragma once\n\n#include <array>\n#include <vkui/core/VkSymbol.h>\n\nnamespace gallery::detail {\n\nstruct VkChosenSymbolDescriptor final {\n    vkui::VkSymbol symbol;\n    const char* label;\n    const char* sourceName;\n};\n\ninline constexpr std::array<VkChosenSymbolDescriptor, ${chosen_count}> kVkChosenSymbols{{\n${chosen_entries}}};\n\n} // namespace gallery::detail\n")
    set(qrc_content "<!-- SPDX-License-Identifier: MIT -->\n<!-- Generated from resources/icons/manifest.json. -->\n<RCC>\n    <qresource prefix=\"/vkui/icons\">\n${qrc_entries}    </qresource>\n</RCC>\n")

    _vkui_write_if_different("${symbol_header}" "${symbol_header_content}")
    _vkui_write_if_different("${registry_header}" "${registry_header_content}")
    _vkui_write_if_different("${chosen_header}" "${chosen_header_content}")
    _vkui_write_if_different("${icon_qrc}" "${qrc_content}")

    set(VKUI_GENERATED_INCLUDE_DIR "${output_dir}/include" PARENT_SCOPE)
    set(VKUI_GENERATED_PRIVATE_DIR "${output_dir}/private" PARENT_SCOPE)
    set(VKUI_GENERATED_GALLERY_DIR "${output_dir}/gallery" PARENT_SCOPE)
    set(VKUI_SYMBOL_HEADER "${symbol_header}" PARENT_SCOPE)
    set(VKUI_SYMBOL_REGISTRY_HEADER "${registry_header}" PARENT_SCOPE)
    set(VKUI_CHOSEN_SYMBOLS_HEADER "${chosen_header}" PARENT_SCOPE)
    set(VKUI_ICON_QRC "${icon_qrc}" PARENT_SCOPE)
endfunction()
